ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'DEPOSIT_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'POST_TRIP_CHARGE_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'CLAIM_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PAYOUT_UPDATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'BOOKING_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TRIP_REMINDER';
